name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

env:
  SPARK_VERSION: 3.1.1
  HADOOP_VERSION: 3.3.1
  HIVE_VERSION: 2.3.7

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: sudo apt-get update
      - name: Install prerequisites
        run: |
          sudo apt-get install openjdk-8-jdk wget curl git -y -q
          sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc && \
          chmod +x mc && \
          mv mc /usr/local/bin/mc
      - name: Get Spark sources
        run: git clone --depth 1 --branch v$SPARK_VERSION https://github.com/apache/spark.git ~/spark
      - run: export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=1g"
      - name: Build Spark from sources
        run: |
          cd ~/spark && \
          ./dev/make-distribution.sh --name custom-spark --tgz \
          -Phadoop-provided -Phive -Phive-thriftserver -Pkubernetes \
          -Dhadoop.version=$HADOOP_VERSION -Dhive.version=$HIVE_VERSION
      - name: Push to S3
        run: |
          mc alias set s3 $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY && \
          mc cp ~/spark/spark-${SPARK_VERSION}-bin-custom-spark.tgz
