name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"

env:
  SPARK_VERSION: 3.5.5
  HADOOP_VERSION: 3.4.1
  HIVE_VERSION: 2.3.9
  JAVA_VERSION: 17
  MAVEN_OPTS: "-Xss256m -Xms4g -Xmx8g -XX:MaxMetaspaceSize=2g -XX:ReservedCodeCacheSize=1g"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - name: Install prerequisites
        run: |
          sudo apt-get install openjdk-${JAVA_VERSION}-jdk wget curl git -y -q
          sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc && \
          sudo chmod +x mc && \
          sudo mv mc /usr/local/bin/mc
      - name: Get Spark sources
        run: git clone --depth 1 --branch v${SPARK_VERSION} https://github.com/apache/spark.git ~/spark
      - name: Build Spark from sources
        run: |
          cd ~/spark && \
          ./dev/make-distribution.sh --name custom-spark --tgz \
          -Phadoop-provided -Phadoop-cloud -Phive -Phive-thriftserver -Pkubernetes -Pvolcano \
          -Dhadoop.version=${HADOOP_VERSION} -Dhive.version=${HIVE_VERSION}
      - name: Push to S3
        run: |
          mc alias set s3 ${{ secrets.AWS_S3_ENDPOINT }} ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          build_name=spark-${SPARK_VERSION}-bin-hadoop-${HADOOP_VERSION}-hive-${HIVE_VERSION}-java-${JAVA_VERSION}.tgz
          mc cp ~/spark/spark-${SPARK_VERSION}-bin-custom-spark.tgz s3/projet-onyxia/build/spark-hive/${build_name}
